### ISSUE TITLE
Error on gen_disguise.py 

### ISSUE THREAD

**Issue by NarenderModi** [sslab-gatech/avpass#13]
kali@localhost:~/avpass/src$ python3.7  gen_disguise.py -i fud.apk  individual
  File "gen_disguise.py", line 40
    print ret_command(OBFUSCATION_LIST[item] ,apkname)        
                    ^
SyntaxError: invalid syntax

**Comment by higoress** [comment]
This code is developed for Python 2.7 environment

**Comment by Amir777228** [comment]
Hi! Can you help me? 
When I introduce python2.7 gen_disguise.py -i client.apk individual 
gives an error message:
Traceback (most recent call last):
  File "gen_disguise.py", line 5, in <module>
    import numpy as np
ImportError: No module named numpy


i installed numpy but it gives the same error

**Comment by higoress** [comment]
are you in linux or windows environment?

**Comment by bhati6734** [comment]
Linux

**Comment by 12-do** [comment]
> Hi! Can you help me? When I introduce python2.7 gen_disguise.py -i client.apk individual gives an error message: Traceback (most recent call last): File "gen_disguise.py", line 5, in import numpy as np ImportError: No module named numpy
> 
> i installed numpy but it gives the same error

go usr/lib/python3/dist-packages/numpy copy numpy folder from there and paste it to usr/lib/dist-packages/python2.7/
