### ISSUE TITLE
smali errors

### ISSUE THREAD

**Issue by labba** [sslab-gatech/avpass#8]
i have a small project that i'm working on that i add new functionality to the BlackBerry Keyboard:
https://mobile.softpedia.com/apk/blackberry-keyboard/#download
i used v3.4.0.15917

this issue also occurs on the actual APK without any changes.

after i have done modification in some AV it was discovered as Virus although there is nothing there.. 

i have tried to use your AVPASS but in the stage of samli it fails due to wrong dalvik code generation.
i have started to fix manually some of the smali issues until i got to the point that a method was created with a " char that is illegal.

so i couldn't fix that..

hope you can help on this..

python gen_disguise.py -i bb.apk individual
[*] Decoding apk file to smali
I: Using Apktool 2.2.3 on bb.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/toor/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
python refl.py -f temp_obfus.apk reflect -c no;
Java reflection for all api invokes in an apk
[*] Loading Smali files list
Loading Smali[else]
[*] Start generating wrappers
[*] Done processing 4348 files => modified 2631 files
[*] Everything done now
python strp.py -f temp_obfus.apk string -c no;
Perturb this APK file
Loading Smali[else]
[*] Start string encoding (all different encryption)
[*] Done processing 4348 files => modified 2714 files
[*] Everything done now
python strp.py -f temp_obfus.apk variable -c no;
Change variable name
Loading Smali[else]
[*] Start variable encryption (simple caesar)
[*] Done processing 4348 files => modified 4345 files
[*] Everything done now
python res.py  -f temp_obfus image -c no;python res.py  -f temp_obfus resxml -c no -n no;
[*] Start image obfuscation
Image file obfuscation - flip pixel
[*] Everything done now
[*] Start Resource XML obfuscation
Loading Smali files list
Generating bb_obfus.apk
I: Using Apktool 2.2.3
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
temp_obfus/smali/com/swiftkey/basl/DateMacro.smali[9,0] missing EOF at '.end field'
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: com/swiftkey/basl/DateMacro.smali
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:75)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:59)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:420)
	at brut.androlib.Androlib.buildSources(Androlib.java:351)
	at brut.androlib.Androlib.build(Androlib.java:307)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:231)
	at brut.apktool.Main.main(Main.java:84)

**Comment by jinhojun** [comment]
1) It seems you applied multiple obfuscation components. Could you change **conf.py** and narrow down problematic component? 

> OBFUSCATION_LIST = [API_REFLECTION, STRING, VARIABLE, RESOURCE_IMAGE+RESOURCE_XML]
> ==> 
> OBFUSCATION_LIST = [API_REFLECTION] or other.
> 

2) Also, there is critical issue with Android Studio. When we developed and conducted evaluation in 2017, most APKs were developed by Android Studio 2.3 (or older version) and **avpass** worked fine. However, **apktool** and **avpass** show mal-functionality on any APK with Android Studio 3.0 (or newer).

**Comment by labba** [comment]
what is your recommended configuration that you would like me to test ?

**Comment by jinhojun** [comment]
You can try to add one component one by one until you test them all.

For example:
1) OBFUSCATION_LIST = [VARIABLE] 
2) OBFUSCATION_LIST = [STRING] 
...

We appreciate your report for any problem. Note that we may not be able to fix API_REFLECTION component because this obfuscation module highly depends on building environment such as version of Android Studio.

**Comment by labba** [comment]
i have done as you recommended

here is my config:
# DEFINED COMMAND: preserve original functionality
STRING         = "python strp.py -f {1}.apk string -c yes;"
VARIABLE       = "python strp.py -f {1}.apk variable -c no;"
PCM            = "python pcm.py  -f {1}.apk package -c no;"
BYTECODE       = "python pcm.py  -f {1}.apk insbyte -c no;" 
BENIGN_CLASS   = "python pcm.py  -f {1}.apk bclass -c no;"
RESOURCE_IMAGE = "python res.py  -f {1} image -c no;"
RESOURCE_XML   = "python res.py  -f {1} resxml -c no -n no;"
API_INTER      = "python api.py  -f {1}.apk inter -a android -c no;"
BEN_PERMISSION = "python api.py  -f {1}.apk bpermission -c no;"
API_REFLECTION = "python refl.py -f {1}.apk reflect -c no;"

ANTI_DATAFLOW  = "WILL RELEASE AFTER ACADEMIC SUBMISSION PROCESS"
COMPONENT_DIV  = "WILL RELEASE AFTER ACADEMIC SUBMISSION PROCESS"
FAMILY_CHANGER = "WILL RELEASE AFTER ACADEMIC SUBMISSION PROCESS"
POLY_STR_ENC   = "WILL RELEASE AFTER ACADEMIC SUBMISSION PROCESS"


# DESTRUCTIVE OBFUSCATIONS: only for inferring feature's impact
RM_RESOURCE_PAYLOAD = "python res.py   -f {1} payload -c no;"
RM_APIS             = "python rmapi.py -f {1}.apk rmall -c no;"
RM_PERMISSION       = "python api.py   -f {1}.apk permission -c no;"


# Obfuscation Group for individual APK disguise
OBFUSCATION_LIST = [STRING]
# Inferring Group
INFERRING_LIST  = [STRING]


here is the output for the apk that i have gave you link for:

toor@toor-virtual-machine:~/avpass/src$ python gen_disguise.py -i bb.apk individual
[*] Decoding apk file to smali
I: Using Apktool 2.2.3 on bb.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /home/toor/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
python strp.py -f temp_obfus.apk string -c yes;
Perturb this APK file
Loading Smali[else]
[*] Start string encoding (all different encryption)
[*] Done processing 4352 files => modified 1274 files
[*] Packing APK...
I: Using Apktool 2.2.3
I: Checking whether sources has changed...
I: Smaling smali folder into classes.dex...
temp_obfus/smali/com/swiftkey/basl/DateMacro.smali[9,0] missing EOF at '.end field'
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: com/swiftkey/basl/DateMacro.smali
	at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:75)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:59)
	at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:36)
	at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:420)
	at brut.androlib.Androlib.buildSources(Androlib.java:351)
	at brut.androlib.Androlib.build(Androlib.java:307)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:231)
	at brut.apktool.Main.main(Main.java:84)
[*] Everything done now
Generating bb_obfus.apk
I: Using Apktool 2.2.3
Exception in thread "main" brut.androlib.AndrolibException: brut.directory.DirectoryException: java.io.FileNotFoundException: temp_obfus (No such file or directory)
	at brut.androlib.Androlib.readMetaFile(Androlib.java:259)
	at brut.androlib.Androlib.build(Androlib.java:271)
	at brut.androlib.Androlib.build(Androlib.java:264)
	at brut.apktool.Main.cmdBuild(Main.java:231)
	at brut.apktool.Main.main(Main.java:84)
Caused by: brut.directory.DirectoryException: java.io.FileNotFoundException: temp_obfus (No such file or directory)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
	at brut.directory.ExtFile.getDirectory(ExtFile.java:52)
	at brut.androlib.Androlib.readMetaFile(Androlib.java:255)
	... 4 more
Caused by: java.io.FileNotFoundException: temp_obfus (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:221)
	at java.util.zip.ZipFile.<init>(ZipFile.java:151)
	at java.util.zip.ZipFile.<init>(ZipFile.java:165)
	at brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
	... 7 more


can you give it a try on your own the link is for a valid market APK and without any changes AVPASS doesn't seems to work at all...

**Comment by jjung63** [comment]
Thanks for the log. I will give it a try.

**Comment by labba** [comment]
hi,
just as a side note, unrelated to the issue i'm seeing it would be better that you would update your code to force while decoding and while building as this:

for decoding:
apktool.bat --force d

and then done for building:
apktool.bat --force-all b

**Comment by jinhojun** [comment]
Thanks for the tip. Actually, we didn't use such a large size APK file as blackberry keyboard (34MB). Currently, I fixed obvious bug but I am also handling another unexpected problems..

Unfortunately, even if I fix that problem, we can't apply AVPASS for the blackberry keyboard APK file because AVPASS is depending on apktool and it returns error when we just smali / baksmali the original program.

**Comment by labba** [comment]
this is why i have told you to add the new command line options since with apktool 2.3.4 i have successfully was able to decode and rebuild without changes only when adding the above options.

so you might also want to update your tools chain to 2.3.4 apktool
